using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using GoPro.Hero.Browser.FileSystem;
using GoPro.Hero.Filtering;

namespace GoPro.Hero
{
    public interface ICameraFacade<T>where T :ICamera<T>,IFilterProvider<T>
    {
        T Camera();

        bool AutoLowLight();
        ICameraFacade<T> AutoLowLight(bool state);
        Task<bool> AutoLowLightAsync();
        Task AutoLowLightAsync(bool state);

        int AvailablePhotoSpace();
        Task<int> AvailablePhotoSpaceAsync();
        TimeSpan AvailableVideoSpace();
        Task<TimeSpan> AvailableVideoSpaceAsync();

        byte BatteryStatus();
        Task<byte> BatteryStatusAsync();

        BeepSound BeepSound();
        ICameraFacade<T> BeepSound(BeepSound beepSound);
        Task<BeepSound> BeepSoundAsync();
        Task BeepSoundAsync(BeepSound beepSound);

        Node Browse();
        BurstRate BurstRate();
        ICameraFacade<T> BurstRate(BurstRate burstRate);
        Task<BurstRate> BurstRateAsync();
        Task BurstRateAsync(BurstRate burstRate);
        ContinuousShot ContinuousShot();
        ICameraFacade<T> ContinuousShot(ContinuousShot continuousShot);
        Task<ContinuousShot> ContinuousShotAsync();
        Task ContinuousShotAsync(ContinuousShot continuousShot);
        Mode DefaultModeOnPowerOn();
        ICameraFacade<T> DefaultModeOnPowerOn(Mode mode);
        Task<Mode> DefaultModeOnPowerOnAsync();
        Task DefaultModeOnPowerOnAsync(Mode mode);
        ICameraFacade<T> DeleteAllFilesOnSdCard();
        Task DeleteAllFilesOnSdCardAsync();
        ICameraFacade<T> DeleteLastFileOnSdCard();
        Task DeleteLastFileOnSdCardAsync();
        FieldOfView FieldOfView();
        ICameraFacade<T> FieldOfView(FieldOfView fieldOfView);
        Task<FieldOfView> FieldOfViewAsync();
        Task FieldOfViewAsync(FieldOfView fieldOfView);
        FrameRate FrameRate();
        ICameraFacade<T> FrameRate(FrameRate frameRate);
        Task<FrameRate> FrameRateAsync();
        Task FrameRateAsync(FrameRate frameRate);
        string FullName();
        Task<string> FullNameAsync();
        LedBlink LedBlink();
        ICameraFacade<T> LedBlink(LedBlink ledBlink);
        Task<LedBlink> LedBlinkAsync();
        Task LedBlinkAsync(LedBlink ledBlink);
        bool LivePreview();
        ICameraFacade<T> LivePreview(bool state);
        Task<bool> LivePreviewAsync();
        Task LivePreviewAsync(bool state);
        bool LivePreviewAvailable();
        Task<bool> LivePreviewAvailableAsync();
        bool Locate();
        ICameraFacade<T> Locate(bool state);
        Task<bool> LocateAsync();
        Task LocateAsync(bool state);
        LoopingVideo LoopingVideo();
        ICameraFacade<T> LoopingVideo(LoopingVideo loopingVideo);
        Task<LoopingVideo> LoopingVideoAsync();
        Task LoopingVideoAsync(LoopingVideo loopingVideo);
        Mode Mode();
        ICameraFacade<T> Mode(Mode mode);
        Task<Mode> ModeAsync();
        Task ModeAsync(Mode mode);
        Orientation Orientation();
        ICameraFacade<T> Orientation(Orientation orientation);
        Task<Orientation> OrientationAsync();
        Task OrientationAsync(Orientation orientation);
        int PhotoCount();
        Task<int> PhotoCountAsync();
        PhotoInVideo PhotoInVideo();
        ICameraFacade<T> PhotoInVideo(PhotoInVideo photoInVideo);
        Task<PhotoInVideo> PhotoInVideoAsync();
        Task PhotoInVideoAsync(PhotoInVideo photoInVideo);
        PhotoResolution PhotoResolution();
        ICameraFacade<T> PhotoResolution(PhotoResolution resolution);
        Task<PhotoResolution> PhotoResolutionAsync();
        Task PhotoResolutionAsync(PhotoResolution resolution);
        bool Power();
        Task<bool> PowerAsync();
        ICameraFacade<T> Power(bool power);
        Task PowerAsync(bool power);
        bool Protune();
        ICameraFacade<T> Protune(bool state);
        Task<bool> ProtuneAsync();
        Task ProtuneAsync(bool state);
        bool Shutter();
        Task<bool> ShutterAsync();
        ICameraFacade<T> Shutter(bool state);
        Task ShutterAsync(bool state);
        SignalStrength SignalStrength();
        Task<SignalStrength> SignalStrengthAsync();
        bool SpotMeter();
        ICameraFacade<T> SpotMeter(bool state);
        Task<bool> SpotMeterAsync();
        Task SpotMeterAsync(bool state);
        bool SupportsAutoLowLight();
        bool SupportsProtune();
        TimeLapse TimeLapse();
        ICameraFacade<T> TimeLapse(TimeLapse timeLapse);
        Task<TimeLapse> TimeLapseAsync();
        Task TimeLapseAsync(TimeLapse timeLapse);
        IEnumerable<bool> ValidAutoLowLight();
        IEnumerable<FieldOfView> ValidFieldOfView();
        IEnumerable<FrameRate> ValidFrameRate();
        IEnumerable<LoopingVideo> ValidLoopingVideo();
        IEnumerable<PhotoResolution> ValidPhotoResolution();
        IEnumerable<bool> ValidProtune();
        IEnumerable<VideoResolution> ValidVideoResolution();
        IEnumerable<WhiteBalance> ValidWhiteBalance();
        int VideoCount();
        Task<int> VideoCountAsync();
        VideoResolution VideoResolution();
        ICameraFacade<T> VideoResolution(VideoResolution resolution);
        Task<VideoResolution> VideoResolutionAsync();
        Task VideoResolutionAsync(VideoResolution resolution);
        VideoStandard VideoStandard();
        ICameraFacade<T> VideoStandard(VideoStandard videoStandard);
        Task<VideoStandard> VideoStandardAsync();
        Task VideoStandardAsync(VideoStandard videoStandard);
        WhiteBalance WhiteBalance();
        ICameraFacade<T> WhiteBalance(WhiteBalance whiteBalance);
        Task<WhiteBalance> WhiteBalanceAsync();
        Task WhiteBalanceAsync(WhiteBalance whiteBalance);

        ICameraFacade<T> Chain(params Func<ICameraFacade<T>, Task>[] fs);
        ICameraFacade<T> Chain<TD>(Func<ICameraFacade<T>, TD> f, out TD output);
        ICameraFacade<T> Chain<TD>(Func<ICameraFacade<T>, Task<TD>> f, out TD output);
        ICameraFacade<T> Chain<TD>(Func<ICameraFacade<T>, TD> f, Action<TD> output);
        ICameraFacade<T> Chain<TD>(Func<ICameraFacade<T>, Task<TD>> f, Action<TD> output);
        Task ChainAsync(params Func<ICameraFacade<T>, Task>[] fs);
        Task ChainAsync<TD>(Func<ICameraFacade<T>, Task<TD>> f, Action<TD> output);
    }
}